### ISSUE TITLE
mac os 10.11.4 无法安装，提示应用程序损坏

### ISSUE THREAD

**Issue by luckyxutao** [yaniswang/hostsPlus#5]
<img width="512" alt="2017-04-25 2 21 26" src="https://cloud.githubusercontent.com/assets/1294316/25371323/d564010e-29c2-11e7-9248-a1e87a5efc04.png">

mac 10.11.4, 重新安装了adobe air也不行 ，删除也不行，提示找不到对应adobe air

**Comment by yaniswang** [comment]
我重新用新版打个包试试

**Comment by CharkeyQK** [comment]
win 10 也遇到这个问题，试过 1.0.2 和 1.0.0 两个版本

**Comment by luckyxutao** [comment]
包打好了吗?

**Comment by yaniswang** [comment]
还没有，这几天感冒了在打点滴。

**Comment by chaijunkun** [comment]
我的Mac10.12.5安装时也遇到了这个问题，后来我在旧的Mac中安装了最新版的hostsplus，然后将app拷贝出来，放在新机器里已经可以用了。已经打包上传到了CSDN，着急用的朋友去下载我的tar包吧，传送门：http://download.csdn.net/detail/chaijunkun/9848060, 不需要资源分

**Comment by CharkeyQK** [comment]
为什么下载了之前的版本也是不能安装？奇怪了

**Comment by yaniswang** [comment]
有可能是操作系统升级后引起的问题。

**Comment by CharkeyQK** [comment]
我在 win 7 试过，也是不行。Adobe air 试过 26 25 18三个版本，hostsPlus 试过1.0.0 1.0.2 0.9.，也是有问题

陈其楷 Charkey
Mobile:+86 18259055729

2017年6月16日 +0800 18:01 Yanis Wang <notifications@github.com>，写道：

**Comment by OOnnnOO** [comment]
win7 +1
看起不错，但安装不了 :sweat_smile:

**Comment by chaijunkun** [comment]
刚刚我下载下来源码，打算自己编译，发现在执行makeExe.bat的时候Adobe Air SDK给出了如下错误提示：Your certificate expired on Thu Apr 06 10:42:09 CST 2017
也就是说源代码里提供的证书在2017年4月6日 10:42:09的时候就过期了。我于是把系统时间调整到了2017年1月1日，发现可以正常编译，原来无法打开的exe安装包也可以正常打开了。大家可以在安装的时候把系统时间改一下，只要改到过期时间之前就可以，安装完再改回来

**Comment by yaniswang** [comment]
感谢楼上，我近期把证书调整下。

**Comment by chaijunkun** [comment]
感谢作者开发出这么好的工具。在Mac下只有你的这款软件最好用。iHost收费，而且还不如hostsplus用起来舒服。如果有可能，真的应该改写成原生的实现方式，然后放到AppStore。如果那样，我第一个支持

**Comment by yaniswang** [comment]
https://github.com/yaniswang/hostsPlus/releases/tag/v1.0.2

已经重新编译过了，大家重新下载下
